"""Heuristic AI-slop detection for posts and replies.

Brand rule: human takes only. No LLM classifiers required, score common
ChatGPT / Claude / Gemini fingerprints and reject or demote.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

# Explicit model self-ID → hard reject
_SELF_ID = re.compile(
    r"("
    r"\bas an ai\b|"
    r"\bas a language model\b|"
    r"\bi'?m (chatgpt|claude|gemini|an ai|a large language model)\b|"
    r"\bi am (chatgpt|claude|gemini|an ai|a large language model)\b|"
    r"\bas chatgpt\b|"
    r"\bgenerated by (chatgpt|ai|an llm)\b"
    r")",
    re.I,
)

# Classic assistant openers / essay glue
_PHRASE_HITS = (
    "certainly!",
    "absolutely!",
    "great question",
    "that's a great question",
    "that's an excellent question",
    "it's important to note",
    "it is important to note",
    "it's worth noting",
    "in conclusion",
    "to summarize",
    "in summary",
    "furthermore",
    "moreover",
    "that being said",
    "with that in mind",
    "in today's world",
    "in today's digital",
    "delve into",
    "delving into",
    "navigate the complexities",
    "landscape of",
    "tapestry of",
    "underscore the importance",
    "underscores the importance",
    "plays a crucial role",
    "plays a pivotal role",
    "multifaceted",
    "holistic approach",
    "leverage synergies",
    "moving forward",
    "at the end of the day",
    "on one hand",
    "on the other hand",
    "both sides of the aisle",
    "it depends on various factors",
    "there are several factors",
    "a nuanced perspective",
    "nuanced take",
    "as an ai language model",
    "i hope this helps",
    "let me know if you need",
    "feel free to ask",
    "happy to help",
    "here are some key points",
    "here are a few thoughts",
    "let's break this down",
    "to put it simply",
)

_EM_DASH = re.compile(r"[—–]")
_NUMBERED_LIST = re.compile(r"(?:^|\n)\s*(?:\d+[\.\)]|\-|\*)\s+\S")
_MULTI_SENTENCE = re.compile(r"[.!?].+[.!?]")


@dataclass(frozen=True)
class AiScore:
    score: int
    likely_ai: bool
    reject: bool
    reasons: tuple[str, ...]


# Thresholds tuned for short Square takes (post/reply ≤500).
FLAG_SCORE = 4
REJECT_SCORE = 8


def score_ai_text(text: str) -> AiScore:
    raw = (text or "").strip()
    if not raw:
        return AiScore(0, False, False, ())

    lower = raw.lower()
    score = 0
    reasons: list[str] = []

    if _SELF_ID.search(raw):
        return AiScore(100, True, True, ("self_id",))

    phrase_hits = 0
    for phrase in _PHRASE_HITS:
        if phrase in lower:
            phrase_hits += 1
    if phrase_hits:
        score += min(6, phrase_hits * 2)
        reasons.append(f"phrases:{phrase_hits}")

    em_count = len(_EM_DASH.findall(raw))
    if em_count >= 1:
        score += 2 + min(2, em_count - 1)
        reasons.append(f"emdash:{em_count}")

    list_hits = len(_NUMBERED_LIST.findall(raw))
    if list_hits >= 2 and len(raw) > 80:
        score += 3
        reasons.append("list_essay")

    # Formal essay voice in a short take: long, multi-clause, few contractions.
    words = re.findall(r"[A-Za-z']+", raw)
    if len(words) >= 28:
        contractions = sum(1 for w in words if "'" in w)
        if contractions == 0 and _MULTI_SENTENCE.search(raw):
            score += 3
            reasons.append("formal_essay")
        if lower.count(",") >= 4 and contractions <= 1:
            score += 2
            reasons.append("comma_heavy")

    # Perfectly balanced both-sides filler for a reply-sized take.
    if "on one hand" in lower and "on the other" in lower:
        score += 4
        reasons.append("both_sides")

    likely = score >= FLAG_SCORE
    reject = score >= REJECT_SCORE
    return AiScore(score, likely, reject, tuple(reasons))


def looks_like_ai(text: str) -> bool:
    return score_ai_text(text).likely_ai


def should_reject_ai(text: str) -> bool:
    return score_ai_text(text).reject


AI_REJECT_DETAIL = (
    "That reads like an AI draft. BarathX is human takes only, "
    "rewrite in your own words and try again."
)
