"""BaratX topic taxonomy — 30 India-trending subtopics per arena (Path C).

Each topic has an RSS query for Google News (IN). Used to seed debate prompts.
"""

from __future__ import annotations

# Default For/Against labels per arena (Startups = YC-style idea validation).
ARENA_DEBATE_SIDES: dict[str, tuple[str, str]] = {
    "sports": ("Agree", "Disagree"),
    "politics": ("Agree", "Disagree"),
    "entertainment": ("Agree", "Disagree"),
    "news": ("Agree", "Disagree"),
    "startups": ("Fund it", "Pass"),
    "spirituality": ("Resonates", "Skeptical"),
}


def debate_sides_for(arena_key: str | None) -> tuple[str, str]:
    return ARENA_DEBATE_SIDES.get(arena_key or "", ("Agree", "Disagree"))


# arena_key → list of {key, name, blurb, rss_query}
TOPICS_BY_ARENA: dict[str, list[dict]] = {
    "sports": [
        {"key": "ipl", "name": "IPL", "blurb": "Auction, matches, rivalries.", "rss_query": "IPL cricket"},
        {"key": "team-india", "name": "Team India", "blurb": "Tests, ODIs, T20.", "rss_query": "Team India cricket"},
        {"key": "world-cup", "name": "World Cup", "blurb": "ICC events and knockouts.", "rss_query": "ICC World Cup cricket"},
        {"key": "wpl", "name": "WPL", "blurb": "Women’s Premier League.", "rss_query": "WPL cricket India"},
        {"key": "football-isl", "name": "Football / ISL", "blurb": "ISL and national football.", "rss_query": "Indian Super League"},
        {"key": "kabaddi", "name": "Kabaddi", "blurb": "Pro Kabaddi heat.", "rss_query": "Pro Kabaddi"},
        {"key": "olympics", "name": "Olympics", "blurb": "India at the Games.", "rss_query": "India Olympics"},
        {"key": "badminton", "name": "Badminton", "blurb": "PV Sindhu, Lakshya, and more.", "rss_query": "India badminton"},
        {"key": "tennis", "name": "Tennis", "blurb": "Grand slams and Davis Cup.", "rss_query": "India tennis"},
        {"key": "hockey", "name": "Hockey", "blurb": "National team and leagues.", "rss_query": "India hockey"},
        {"key": "athletics", "name": "Athletics", "blurb": "Track, field, Neeraj.", "rss_query": "India athletics Neeraj"},
        {"key": "wrestling", "name": "Wrestling", "blurb": "Olympics and nationals.", "rss_query": "India wrestling"},
        {"key": "boxing", "name": "Boxing", "blurb": "Amateur and pro fights.", "rss_query": "India boxing"},
        {"key": "chess", "name": "Chess", "blurb": "India’s grandmaster wave.", "rss_query": "India chess Gukesh"},
        {"key": "f1", "name": "F1 / Motorsport", "blurb": "Racing and Indian fans.", "rss_query": "Formula 1"},
        {"key": "nba", "name": "NBA", "blurb": "US basketball for India fans.", "rss_query": "NBA"},
        {"key": "esports", "name": "Esports", "blurb": "BGMI, Valorant, tournaments.", "rss_query": "India esports BGMI"},
        {"key": "ucl", "name": "Champions League", "blurb": "Europe nights.", "rss_query": "UEFA Champions League"},
        {"key": "sports-business", "name": "Sports Business", "blurb": "Rights, brands, salaries.", "rss_query": "India sports business"},
        {"key": "fantasy", "name": "Fantasy Sports", "blurb": "Dream11 and hot takes.", "rss_query": "Dream11 fantasy cricket"},
        {"key": "women-sports", "name": "Women's Sports", "blurb": "Beyond cricket.", "rss_query": "India women sports"},
        {"key": "local-sports", "name": "City Sports", "blurb": "Local leagues and school sports.", "rss_query": "India local sports league"},
        {"key": "fitness", "name": "Fitness & Running", "blurb": "Marathons and gym culture.", "rss_query": "India marathon fitness"},
        {"key": "cricket-domestic", "name": "Domestic Cricket", "blurb": "Ranji and state cricket.", "rss_query": "Ranji Trophy"},
        {"key": "coaching", "name": "Coaching & Selection", "blurb": "Selectors and coaches.", "rss_query": "India cricket selection coach"},
        {"key": "stadiums", "name": "Stadiums & Fans", "blurb": "Crowds, tickets, vibes.", "rss_query": "India cricket stadium fans"},
        {"key": "para-sports", "name": "Para Sports", "blurb": "Paralympics and inclusion.", "rss_query": "India Paralympics"},
        {"key": "ufc", "name": "Combat Sports", "blurb": "MMA, UFC, and more.", "rss_query": "UFC MMA India"},
        {"key": "golf", "name": "Golf", "blurb": "Indian golfers and tours.", "rss_query": "India golf"},
        {"key": "table-tennis", "name": "Table Tennis", "blurb": "TT and paddles.", "rss_query": "India table tennis"},
    ],
    "politics": [
        {"key": "national", "name": "National Politics", "blurb": "Parliament and parties.", "rss_query": "India politics Parliament"},
        {"key": "elections", "name": "Elections", "blurb": "Votes, campaigns, results.", "rss_query": "India elections"},
        {"key": "policy", "name": "Policy", "blurb": "Bills, reforms, schemes.", "rss_query": "India government policy"},
        {"key": "economy-pol", "name": "Economy & Budget", "blurb": "Budget and growth fights.", "rss_query": "India Union Budget"},
        {"key": "foreign-policy", "name": "Foreign Policy", "blurb": "Neighbours and world stage.", "rss_query": "India foreign policy"},
        {"key": "state-politics", "name": "State Politics", "blurb": "CM fights and assemblies.", "rss_query": "India state elections"},
        {"key": "judiciary", "name": "Judiciary", "blurb": "Courts and constitution.", "rss_query": "India Supreme Court"},
        {"key": "defence", "name": "Defence", "blurb": "Forces and security.", "rss_query": "India defence"},
        {"key": "farmers", "name": "Farmers", "blurb": "Agri policy and protests.", "rss_query": "India farmers protest policy"},
        {"key": "jobs", "name": "Jobs & Youth", "blurb": "Employment and exams.", "rss_query": "India unemployment jobs"},
        {"key": "education-pol", "name": "Education Policy", "blurb": "NEP, exams, campuses.", "rss_query": "India education policy NEP"},
        {"key": "health-pol", "name": "Health Policy", "blurb": "Public health and insurance.", "rss_query": "India health policy"},
        {"key": "infra", "name": "Infrastructure", "blurb": "Roads, rail, cities.", "rss_query": "India infrastructure projects"},
        {"key": "digital-india", "name": "Digital India", "blurb": "Gov tech and data.", "rss_query": "Digital India UPI"},
        {"key": "caste-religion", "name": "Social Issues", "blurb": "Identity and society debates.", "rss_query": "India social issues politics"},
        {"key": "media-pol", "name": "Media & Free Speech", "blurb": "Press, platforms, speech.", "rss_query": "India free speech media"},
        {"key": "climate-pol", "name": "Climate Policy", "blurb": "Energy and environment law.", "rss_query": "India climate policy"},
        {"key": "urban", "name": "Urban Governance", "blurb": "Cities, civic bodies.", "rss_query": "India smart cities municipal"},
        {"key": "women-pol", "name": "Women & Politics", "blurb": "Representation and rights.", "rss_query": "India women reservation politics"},
        {"key": "corruption", "name": "Corruption & Scams", "blurb": "Accountability debates.", "rss_query": "India corruption scam"},
        {"key": "tax", "name": "Tax & GST", "blurb": "Rates, reforms, compliance.", "rss_query": "India GST tax reform"},
        {"key": "federalism", "name": "Centre–State", "blurb": "Federal fights and funds.", "rss_query": "India centre state politics"},
        {"key": "border", "name": "Border & Security", "blurb": "Borders and internal security.", "rss_query": "India border security"},
        {"key": "labour", "name": "Labour & Unions", "blurb": "Workers and labour codes.", "rss_query": "India labour code unions"},
        {"key": "reservation", "name": "Reservation", "blurb": "Quota debates.", "rss_query": "India reservation quota"},
        {"key": "language-pol", "name": "Language Politics", "blurb": "Hindi, regional languages.", "rss_query": "India language politics"},
        {"key": "privacy", "name": "Data & Privacy", "blurb": "DPDP and surveillance.", "rss_query": "India data privacy DPDP"},
        {"key": "local-body", "name": "Local Body Polls", "blurb": "Municipal and panchayat.", "rss_query": "India municipal elections"},
        {"key": "diaspora-pol", "name": "Diaspora Politics", "blurb": "NRIs and overseas India.", "rss_query": "India diaspora politics"},
        {"key": "youth-pol", "name": "Youth Politics", "blurb": "Campus and first-time voters.", "rss_query": "India youth politics campus"},
    ],
    "entertainment": [
        {"key": "bollywood", "name": "Bollywood", "blurb": "Hindi film fights.", "rss_query": "Bollywood"},
        {"key": "tollywood", "name": "Tollywood", "blurb": "Telugu cinema.", "rss_query": "Tollywood Telugu cinema"},
        {"key": "kollywood", "name": "Kollywood", "blurb": "Tamil cinema.", "rss_query": "Kollywood Tamil cinema"},
        {"key": "mollywood", "name": "Mollywood", "blurb": "Malayalam cinema.", "rss_query": "Mollywood Malayalam cinema"},
        {"key": "sandalwood", "name": "Sandalwood", "blurb": "Kannada cinema.", "rss_query": "Sandalwood Kannada cinema"},
        {"key": "ott", "name": "OTT / Streaming", "blurb": "Netflix, Prime, hot takes.", "rss_query": "India OTT Netflix Prime"},
        {"key": "music", "name": "Music", "blurb": "Albums, concerts, charts.", "rss_query": "India music Bollywood songs"},
        {"key": "reality-tv", "name": "Reality TV", "blurb": "Bigg Boss and contests.", "rss_query": "Bigg Boss India"},
        {"key": "celebrity", "name": "Celebrity", "blurb": "Stars and controversies.", "rss_query": "Bollywood celebrity news"},
        {"key": "web-series", "name": "Web Series", "blurb": "Indian originals.", "rss_query": "Indian web series"},
        {"key": "comedy", "name": "Comedy", "blurb": "Stand-up and sketches.", "rss_query": "India stand up comedy"},
        {"key": "gaming-ent", "name": "Gaming Culture", "blurb": "Creators and streams.", "rss_query": "India gaming YouTube"},
        {"key": "fashion", "name": "Fashion", "blurb": "Style and red carpets.", "rss_query": "India fashion Bollywood"},
        {"key": "awards", "name": "Awards", "blurb": "Filmfare, National, Oscars.", "rss_query": "Filmfare Awards India"},
        {"key": "theatre", "name": "Theatre & Arts", "blurb": "Stage and culture.", "rss_query": "India theatre arts"},
        {"key": "regional-ent", "name": "Regional Stars", "blurb": "Beyond the metros.", "rss_query": "Indian regional cinema"},
        {"key": "memes", "name": "Memes & Internet", "blurb": "Viral culture.", "rss_query": "India memes viral"},
        {"key": "podcasts", "name": "Podcasts", "blurb": "Audio culture.", "rss_query": "India podcasts"},
        {"key": "dance", "name": "Dance", "blurb": "Classical to reality shows.", "rss_query": "India dance reality show"},
        {"key": "indie", "name": "Indie & Alternative", "blurb": "Indie film and music.", "rss_query": "India indie film music"},
        {"key": "kpop", "name": "K-pop / Global Pop", "blurb": "Global fandom in India.", "rss_query": "K-pop India"},
        {"key": "punjabi", "name": "Punjabi Music", "blurb": "Charts and concerts.", "rss_query": "Punjabi music India"},
        {"key": "youtube", "name": "YouTubers", "blurb": "Creators and drama.", "rss_query": "India YouTube creators"},
        {"key": "box-office", "name": "Box Office", "blurb": "Hits, flops, openings.", "rss_query": "India box office"},
        {"key": "south-pan", "name": "Pan-India Films", "blurb": "Dubbed blockbusters.", "rss_query": "Pan India film"},
        {"key": "tv-serials", "name": "TV Serials", "blurb": "Daily soaps and TRPs.", "rss_query": "India TV serials"},
        {"key": "sports-ent", "name": "Sports Entertainment", "blurb": "WWE, kabaddi showbiz.", "rss_query": "WWE India sports entertainment"},
        {"key": "literature", "name": "Books & Lit", "blurb": "Authors and bestsellers.", "rss_query": "India books literature"},
        {"key": "festivals-ent", "name": "Film Festivals", "blurb": "IFFI, MAMI, and more.", "rss_query": "India film festival"},
        {"key": "influencer", "name": "Influencers", "blurb": "Instagram / reel fame.", "rss_query": "India influencers Instagram"},
    ],
    "news": [
        {"key": "breaking", "name": "Breaking", "blurb": "What just happened.", "rss_query": "India breaking news"},
        {"key": "business", "name": "Business", "blurb": "Markets and companies.", "rss_query": "India business markets"},
        {"key": "tech", "name": "Tech", "blurb": "Gadgets and big tech.", "rss_query": "India technology news"},
        {"key": "startup-news", "name": "Startup News", "blurb": "Funding headlines.", "rss_query": "India startup funding"},
        {"key": "markets", "name": "Markets", "blurb": "Sensex, Nifty, crypto.", "rss_query": "Nifty Sensex India"},
        {"key": "science", "name": "Science", "blurb": "Research and discovery.", "rss_query": "India science research"},
        {"key": "climate", "name": "Climate", "blurb": "Weather and environment.", "rss_query": "India climate weather"},
        {"key": "health", "name": "Health", "blurb": "Public health stories.", "rss_query": "India health news"},
        {"key": "education", "name": "Education", "blurb": "Exams, colleges, edtech.", "rss_query": "India education news JEE"},
        {"key": "crime", "name": "Crime", "blurb": "Law and order stories.", "rss_query": "India crime news"},
        {"key": "cities", "name": "Cities", "blurb": "Metro life and civic news.", "rss_query": "Mumbai Delhi Bangalore news"},
        {"key": "world", "name": "World", "blurb": "Global news India cares about.", "rss_query": "world news India"},
        {"key": "opinion", "name": "Opinion", "blurb": "Editorials worth fighting.", "rss_query": "India opinion editorial"},
        {"key": "factcheck", "name": "Fact Check", "blurb": "Claims vs evidence.", "rss_query": "India fact check"},
        {"key": "transport", "name": "Transport", "blurb": "Rail, air, roads.", "rss_query": "India railways aviation"},
        {"key": "energy", "name": "Energy", "blurb": "Power, oil, renewables.", "rss_query": "India energy renewable"},
        {"key": "agriculture", "name": "Agriculture", "blurb": "Farms and food prices.", "rss_query": "India agriculture news"},
        {"key": "space", "name": "Space", "blurb": "ISRO missions.", "rss_query": "ISRO space mission"},
        {"key": "ai", "name": "AI & Future", "blurb": "AI in India and work.", "rss_query": "AI India technology"},
        {"key": "cyber", "name": "Cyber & Scams", "blurb": "Fraud and digital safety.", "rss_query": "India cyber crime scam"},
        {"key": "weather", "name": "Monsoon & Disasters", "blurb": "Floods, heat, alerts.", "rss_query": "India monsoon floods"},
        {"key": "inflation", "name": "Prices & Inflation", "blurb": "Fuel, food, cost of living.", "rss_query": "India inflation prices"},
        {"key": "jobs-news", "name": "Jobs News", "blurb": "Hiring and layoffs.", "rss_query": "India jobs hiring layoffs"},
        {"key": "real-estate", "name": "Real Estate", "blurb": "Housing and rents.", "rss_query": "India real estate housing"},
        {"key": "auto", "name": "Auto & EV", "blurb": "Cars, bikes, EVs.", "rss_query": "India EV automobiles"},
        {"key": "telecom", "name": "Telecom", "blurb": "5G, Jio, Airtel.", "rss_query": "India telecom 5G"},
        {"key": "banking", "name": "Banking", "blurb": "Banks, RBI, credit.", "rss_query": "RBI India banking"},
        {"key": "defence-news", "name": "Defence News", "blurb": "Forces and geopolitics.", "rss_query": "India defence news"},
        {"key": "viral", "name": "Viral India", "blurb": "Stories everyone shared.", "rss_query": "India viral news"},
        {"key": "investigations", "name": "Investigations", "blurb": "Longform and probes.", "rss_query": "India investigation news"},
    ],
    # YC-style public square: pitch ideas, India votes Fund it / Pass.
    "startups": [
        {"key": "pitch-validation", "name": "Pitch Validation", "blurb": "Drop an idea. Get Fund it / Pass.", "rss_query": "India startup idea pitch"},
        {"key": "yc-accelerators", "name": "YC & Accelerators", "blurb": "YC, Sequoia Arc, Surge, and more.", "rss_query": "Y Combinator India accelerator"},
        {"key": "fundraising", "name": "Fundraising", "blurb": "Seed to Series rounds.", "rss_query": "India startup funding round"},
        {"key": "ai-startups", "name": "AI Startups", "blurb": "Indic models, agents, infra.", "rss_query": "India AI startup funding Sarvam"},
        {"key": "deeptech", "name": "Deep Tech", "blurb": "Chips, robotics, hard science.", "rss_query": "India deeptech startup"},
        {"key": "fintech", "name": "Fintech", "blurb": "Payments, lending, UPI rails.", "rss_query": "India fintech startup"},
        {"key": "saas", "name": "SaaS / B2B", "blurb": "Global SaaS from India.", "rss_query": "India SaaS startup"},
        {"key": "d2c", "name": "D2C Brands", "blurb": "Beauty, health, unit economics.", "rss_query": "India D2C brand startup"},
        {"key": "quick-commerce", "name": "Quick Commerce", "blurb": "10-minute delivery wars.", "rss_query": "India quick commerce"},
        {"key": "healthtech", "name": "Healthtech", "blurb": "Care, diagnostics, medtech.", "rss_query": "India healthtech startup"},
        {"key": "edtech", "name": "Edtech", "blurb": "Learning after the boom.", "rss_query": "India edtech startup"},
        {"key": "climate-tech", "name": "Climate Tech", "blurb": "Clean energy and carbon.", "rss_query": "India climate tech startup"},
        {"key": "space-tech", "name": "Space Tech", "blurb": "Private space and satellites.", "rss_query": "India space tech startup"},
        {"key": "defence-tech", "name": "Defence Tech", "blurb": "Dual-use and defence startups.", "rss_query": "India defence startup"},
        {"key": "semicon", "name": "Semiconductors", "blurb": "Design, packaging, fab dreams.", "rss_query": "India semiconductor startup"},
        {"key": "agritech", "name": "Agritech", "blurb": "Farms, supply chains, tech.", "rss_query": "India agritech startup"},
        {"key": "logistics", "name": "Logistics", "blurb": "Supply chain and mobility.", "rss_query": "India logistics startup"},
        {"key": "wealthtech", "name": "Wealthtech", "blurb": "Investing for mass affluent India.", "rss_query": "India wealthtech startup"},
        {"key": "insurtech", "name": "Insurtech", "blurb": "Insurance distribution tech.", "rss_query": "India insurtech startup"},
        {"key": "unit-economics", "name": "Unit Economics", "blurb": "Burn, CAC, LTV fights.", "rss_query": "India startup unit economics"},
        {"key": "product-market-fit", "name": "Product-Market Fit", "blurb": "Do users actually want it?", "rss_query": "startup product market fit"},
        {"key": "founder-stories", "name": "Founder Stories", "blurb": "Builds, pivots, exits.", "rss_query": "India startup founder"},
        {"key": "layoffs-hiring", "name": "Hiring & Layoffs", "blurb": "Talent market reality.", "rss_query": "India startup layoffs hiring"},
        {"key": "ipo-exits", "name": "IPO & Exits", "blurb": "Listings and M&A.", "rss_query": "India startup IPO OYO Zepto"},
        {"key": "tier2-startups", "name": "Tier-2 / Bharat", "blurb": "Building beyond metros.", "rss_query": "India Tier 2 startup Bharat"},
        {"key": "women-founders", "name": "Women Founders", "blurb": "Capital and representation.", "rss_query": "India women founders startups"},
        {"key": "regtech", "name": "Policy & Regtech", "blurb": "DPI, compliance, regulation.", "rss_query": "India startup regulation DPI"},
        {"key": "investor-takes", "name": "Investor Takes", "blurb": "What VCs are funding now.", "rss_query": "India venture capital 2026"},
        {"key": "ev-mobility", "name": "EV & Mobility", "blurb": "EVs, charging, mobility.", "rss_query": "India EV startup mobility"},
        {"key": "global-from-india", "name": "Global from Day One", "blurb": "India-built, world-sold.", "rss_query": "India global SaaS startup"},
    ],
    "spirituality": [
        {"key": "bhajan-clubbing", "name": "Bhajan Clubbing", "blurb": "Gen Z devotion meets nightlife.", "rss_query": "bhajan clubbing India"},
        {"key": "yoga", "name": "Yoga", "blurb": "Practice, teachers, International Day.", "rss_query": "yoga India"},
        {"key": "meditation", "name": "Meditation", "blurb": "Mindfulness and apps.", "rss_query": "meditation mindfulness India"},
        {"key": "ayurveda", "name": "Ayurveda", "blurb": "Traditional wellness systems.", "rss_query": "Ayurveda India"},
        {"key": "spiritual-tourism", "name": "Spiritual Tourism", "blurb": "Pilgrimage + wellness travel.", "rss_query": "India spiritual tourism pilgrimage"},
        {"key": "kumbh", "name": "Kumbh & Melas", "blurb": "Mass gatherings and faith.", "rss_query": "Kumbh Mela India"},
        {"key": "temples", "name": "Temples & Darshan", "blurb": "Mandirs, queues, miracles.", "rss_query": "India temple darshan"},
        {"key": "astrology", "name": "Astrology", "blurb": "Charts, planets, apps.", "rss_query": "astrology India"},
        {"key": "festivals", "name": "Festivals", "blurb": "Diwali, Holi, Navratri, and more.", "rss_query": "India festival celebration"},
        {"key": "bhakti", "name": "Bhakti & Kirtan", "blurb": "Devotional music and satsang.", "rss_query": "kirtan bhakti India"},
        {"key": "gurus", "name": "Gurus & Teachers", "blurb": "Spiritual leaders and debates.", "rss_query": "India spiritual guru"},
        {"key": "vedanta", "name": "Vedanta & Philosophy", "blurb": "Ideas that shape seekers.", "rss_query": "Vedanta philosophy India"},
        {"key": "buddhism", "name": "Buddhism", "blurb": "Heritage circuits and practice.", "rss_query": "Buddhism India"},
        {"key": "sikhism", "name": "Sikhism", "blurb": "Gurdwaras and seva.", "rss_query": "Sikhism Gurdwara India"},
        {"key": "islam-sufi", "name": "Sufi & Islam", "blurb": "Sufi traditions and community.", "rss_query": "Sufi Islam India"},
        {"key": "christianity", "name": "Christianity", "blurb": "Churches and community life.", "rss_query": "Christianity India church"},
        {"key": "jainism", "name": "Jainism", "blurb": "Ahimsa and practice.", "rss_query": "Jainism India"},
        {"key": "pilgrimage", "name": "Pilgrimage Routes", "blurb": "Char Dham, Tirupati, Amarnath.", "rss_query": "India pilgrimage Char Dham Tirupati"},
        {"key": "rishikesh", "name": "Rishikesh & Ashrams", "blurb": "Ashram life and retreats.", "rss_query": "Rishikesh ashram yoga"},
        {"key": "varanasi", "name": "Varanasi & Sacred Cities", "blurb": "Ganga and holy towns.", "rss_query": "Varanasi spiritual India"},
        {"key": "breathwork", "name": "Breathwork & Pranayama", "blurb": "Breath as practice.", "rss_query": "pranayama breathwork India"},
        {"key": "sound-healing", "name": "Sound Healing", "blurb": "Bowls, chants, sound baths.", "rss_query": "sound healing India"},
        {"key": "mental-spiritual", "name": "Faith & Mental Health", "blurb": "Where wellness meets belief.", "rss_query": "spirituality mental health India"},
        {"key": "gen-z-faith", "name": "Gen Z Faith", "blurb": "How young India believes.", "rss_query": "Gen Z spirituality India"},
        {"key": "interfaith", "name": "Interfaith", "blurb": "Dialogue across traditions.", "rss_query": "interfaith India"},
        {"key": "rituals", "name": "Rituals & Puja", "blurb": "Home and temple practice.", "rss_query": "puja rituals India"},
        {"key": "scripture", "name": "Scripture & Study", "blurb": "Gita, Quran, Bible, and more.", "rss_query": "Bhagavad Gita scripture India"},
        {"key": "wellness-retreats", "name": "Wellness Retreats", "blurb": "Retreats that mix spa + spirit.", "rss_query": "India wellness spiritual retreat"},
        {"key": "seva", "name": "Seva & Charity", "blurb": "Service as spiritual practice.", "rss_query": "seva charity India"},
        {"key": "digital-faith", "name": "Digital Faith", "blurb": "Online satsang and apps.", "rss_query": "spirituality app India online"},
    ],
}


def all_topics() -> list[dict]:
    out = []
    for arena_key, rows in TOPICS_BY_ARENA.items():
        for row in rows:
            out.append({**row, "arena_key": arena_key})
    return out
